name: Deploy Weeek Tg App

on:
  push:
    branches: [ dev ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2 # Проверить код из репозитория

    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '21.6.1' # Указать версию Node.js

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Setup known_hosts
      run: |
        mkdir -p ~/.ssh
        echo "185.185.70.149 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBHLTK5m505P8D19JOUQIJKFFDPhzuzf4k0wPgwUOwXtbKCv2l0l7uLJ90SuRorRmrq3w1CMKTUox9PkzU7fis0A=" >> ~/.ssh/known_hosts

      

    - name: Deploy to Server
      run: |
        eval "$(ssh-agent -s)"
        ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"
        scp -rv ./build/* levpavloff@185.185.70.149:/var/www/projects/webapp


